# Generated by Django 2.1.2 on 2018-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('imageurl', models.URLField(max_length=300)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('source_url', models.URLField(max_length=300)),
                ('source_id', models.IntegerField()),
            ],
        ),
    ]
