# Generated by Django 2.1.2 on 2018-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptonews',
            name='source_id',
            field=models.CharField(max_length=20),
        ),
    ]
