# Generated by Django 2.1.2 on 2018-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20181007_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptonews',
            name='sentiment',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
